# 开发环境

server:
  port: 8088

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost/blog?useSSL=FALSE&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  #静态资源访问路径
  mvc:
    static-path-pattern: /**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.quan.blog.entity
  configuration:
   mapUnderscoreToCamelCase : true

#showSql
logging:
  level:
    com.quan.blog.dao: debug
  file: log/blog-dev.log

comment:
 avatar: /images/test.jpg


