# 生产环境
server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost/blog?useSSL=FALSE&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  #静态资源访问路径
  mvc:
    static-path-pattern: /**

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.quan.blog.entity

#showSql
logging:
  level:
    root: warn
    com.quan.blog: info
  file: log/blog-pro.log